CREATE TABLE USERS (
  ID BIGSERIAL PRIMARY KEY,
  USERNAME VARCHAR(64) UNIQUE NOT NULL,
  PASSWORD VARCHAR(128) NOT NULL,
  CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_LOGIN_TIME TIMESTAMP
);

CREATE TABLE ACCOUNT (
  ID BIGSERIAL PRIMARY KEY,
  USERS_ID BIGSERIAL NOT NULL REFERENCES USERS(ID),
  NAME VARCHAR(128) NOT NULL,
  DESCRIPTION VARCHAR(4096),
  CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TYPE EVENT_TYPE AS ENUM ('transfer', 'change');

CREATE TABLE EVENT (
  ID BIGSERIAL PRIMARY KEY,
  ACCOUNT_ID BIGSERIAL NOT NULL REFERENCES ACCOUNT(ID),
  DESCRIPTION VARCHAR(128),
  AMOUNT NUMERIC(14,2) NOT NULL,
  CUMULATIVE_AMOUNT NUMERIC(14,2),
  CHANGE_TYPE VARCHAR(32) NOT NULL,
  EVENT_DATE DATE NOT NULL
);