CREATE TABLE USERS (
  ID BIGSERIAL PRIMARY KEY,
  USERNAME VARCHAR(64) UNIQUE NOT NULL,
  PASSWORD VARCHAR(128) NOT NULL,
  CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_LOGIN_TIME TIMESTAMP
);

CREATE TABLE ACCOUNT (
  ID BIGSERIAL PRIMARY KEY,
  USERS_ID BIGSERIAL NOT NULL REFERENCES USERS(ID),
  NAME VARCHAR(128) NOT NULL,
  DESCRIPTION VARCHAR(4096),
  CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);